name: Deploy Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name myResourceGroup --location eastus

      - name: Create Virtual Machine
        run: |
          az vm create \
            --resource-group myResourceGroup \
            --name myVM \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --generate-ssh-keys \
            --size Standard_B1s 
